version: 2

sources:
  Dataset: gz_raw_data
  Tables:
    raw_gz_sales
    raw_gz_product
    raw_gz_ship

rename sources:
  Dataset: raw
  Tables:
    sales
    product
    ship

select *
from {{source(’raw’, ‘sales’)}}

with

 source as (

     select * from {{ source('raw', 'sales') }}

 ),

 renamed as (

     select
         date_date,
         orders_id,
         pdt_id,
         revenue,
         quantity

     from source

 )

 select * from renamed